rcgsheffield/hpc-changelog

_includes/footer.html, _includes/header.html, _includes/post.html, _sass/_custom-styles.scss
Multiple style improvements covering:
https://github.com/rcgsheffield/hpc-changelog/issues/3
https://github.com/rcgsheffield/hpc-changelog/issues/4
https://github.com/rcgsheffield/hpc-changelog/issues/6
https://github.com/rcgsheffield/hpc-changelog/issues/7
https://github.com/rcgsheffield/hpc-changelog/issues/8
=> Multiple small style improvements

Gemfile, Gemfile.lock, _config.yml, _includes/post.html, _layouts/archive-categories.html, _layouts/archive-days.html, _layouts/archive-months.html, _layouts/archive-years.html
Adds the summary pages by day, month, year and adjusts the date links on posts to be aimed at the correct date page.
=> Initial add for archived / dated summary pages.

tags.html
Accidentally missed this correction in the STAR PR.
=> Add correction for tag cloud page for case sensitivity.

_posts/2022-01-04-Bowtie2-bessemer-install.md
Add Bowtie 2 info and also test the build process when the autogenerated files are not pre-added. (tag / feed md files.)
=> Add Bowtie2 info.

_includes/header.html
=> Add HPC docs link using class margin for separation in header.

_posts/2022-01-17-docs-update-install-instructions.md, _tags/documentation.md, _tags/update.md, feeds/tags/documentation.xml, feeds/tags/update.xml
Contains the signposting of the new software installation guidance.
=> Adds first HPC documentation change - includes new tags.

_posts/2022-01-25-NetLogo-bessemer.md, _tags/NetLogo.md, feeds/tags/NetLogo.xml
=> NetLogo install on Bessemer

Gemfile, Gemfile.lock, _posts/2022-02-09-bessemer-preemptable-jobs.md
=> Ensure webrick installed for serving site locally

_config.yml, hpc-changelog/index.html
Update for https://changelog.hpc.shef.ac.uk/
=> Adjustment is made in _config.yml for new domain.

_posts/2022-02-11-matlab-bessemer-sharc-new-version.md, _tags/MATLAB.md, feeds/tags/MATLAB.xml
New version of MATLAB 2021b installed on both clusters.
=> MATLAB 2021b update

_posts/2022-02-16-CUDA-cuDNN-bessemer-new-versions.md, _tags/CUDA.md, _tags/cuDNN.md, feeds/tags/CUDA.xml, feeds/tags/cuDNN.xml
=> CUDA versions 11.0.2, 11.1.1 and matching cuDNN version 8.0.4.30 added.

README.md, _posts/2021-12-21-STAR-bessemer-install.md, _posts/2022-01-04-Bowtie2-bessemer-install.md, _posts/2022-01-07-ncdu-bessemer-sharc-install.md, _posts/2022-01-17-docs-update-install-instructions.md, _posts/2022-01-25-NetLogo-bessemer.md, _posts/2022-02-01-docs-update-file-transfer.md, _posts/2022-02-11-matlab-bessemer-sharc-new-version.md, _posts/2022-02-16-CUDA-cuDNN-bessemer-new-versions.md, _posts/2022-03-24-JAGS-bessemer-install.md, _posts/2022-04-04-DL_POLY4_PLUMED-bessemer-install copy.md, _tags/ansys.md, _tags/bessemer.md, _tags/bug.md, _tags/sharc.md, _tags/testing.md, feeds/tags/ansys.xml, feeds/tags/bessemer.xml, feeds/tags/bug.xml, feeds/tags/sharc.xml, feeds/tags/testing.xml
Refactor to match cluster tags and minor clarification on the readme to signpost the prehook bug.
Removal of additional spurious tags.
=> Match tag case sensitivity and clarify readme.

_posts/2022-04-21-SoX-Bessemer.md, _tags/SoX.md, feeds/tags/SoX.xml
=> SoX added to Bessemer.

_posts/2022-09-01-bessemer-filestore-maintenance.md
Adding the Bessemer fastdata area maintenance.
=> Maintenance 1st Sept 2022

_posts/2022-09-01-bessemer-filestore-maintenance.md
"At risk" on its own while going offline sounds like we're doing something risky to data rather than regular(ish) maintenance.
=> Amend wording for Bessemer fastdata maintenance.

_posts/2023-01-30-software-git-upgrades.md, _tags/Git.md, feeds/tags/Git.xml
Pending on installations finishing.
=> Git updates / depreciations.

_posts/2023-04-19-stanage-launch.md, _tags/Stanage.md, feeds/tags/Stanage.xml
=> Stanage launch

_posts/2024-03-12-nextflow-stanage-update.md, _tags/Nextflow.md, feeds/tags/Nextflow.xml
=> Nextflow 23.10.0

_posts/2024-10-14-Stanage-GPU-driver-updates---version-550.90.12-now-available.md, _tags/H100.md, create_new_post.sh, feeds/tags/H100.xml
As above.
This PR also includes a new helper script which should be fairly self explanatory via comments.
=> Stanage GPU driver update - Driver ver 550.90.12, CUDA 12.4

_posts/2024-10-29-Stanage-and-Bessemer-HPC-GPU-Driver-updates.md, _posts/2024-10-29-Stanage-central-software-storage-volume-nonn-disruptive-maintenance.md
* GPU driver updates (again).
* /opt/apps/ volume capacity increase.
=> Add upcoming maintenance events

_posts/2024-10-29-Stanage-and-Bessemer-HPC-GPU-Driver-updates.md
=> Correct spelling error.

_includes/footer.html
Fix incorrectly templated URL with specific URL.
=> Fix incorrectly templated URL with specific URL.

_config.yml
Amends the permalink config setting to avoid duplicate filenames when generating HTML files.
=> Implement adjusted HTML filename creation

_posts/2025-02-11-bessemer-slurm-maintenance-2.md
=> Bessemer HPC system planned (non-disruptive) maintenance: Slurm scheduler upgrade - February 13, 2025 between 11:00 and 13:00

_posts/2025-02-11-bessemer-slurm-maintenance-2.md
=> Maintenance update on previous notification.
